name: dsml20
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Created by running the following commands on Linux, macOS and Windows, then taking the common subset of dependencies.
  # conda create -n ntds_2019 python=3.7 jupyterlab git numpy scipy matplotlib-base pandas networkx pygsp scikit-learn pytorch cpuonly dgl requests -c dglteam -c pytorch -c conda-forge -c defaults --override-channels
  # conda env export --no-builds -n ntds_2019 > environment_linux.yml
  - pip
  - pandas
  - matplotlib 
  - scikit-learn
  - spyder
  - pytest
  - jupyter
  - networkx
  - pytorch=1.6.0
  - torchvision=0.7.0
  - cudatoolkit=10.2
  #- cpuonly # replace cpuonly with your cuda version for GPU support
  - future
  - pillow
  - tensorboard
  - seaborn
  - pip: 
    - h5py
    - torch-scatter==latest+cu102 -f https://pytorch-geometric.com/whl/torch-1.6.0.html
    - torch-sparse==latest+cu102 -f https://pytorch-geometric.com/whl/torch-1.6.0.html
    - torch-cluster==latest+cu102 -f https://pytorch-geometric.com/whl/torch-1.6.0.html
    - torch-spline-conv==latest+cu102 -f https://pytorch-geometric.com/whl/torch-1.6.0.html
    - torch-geometric